# Generated by Django 2.2.7 on 2019-11-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('clothing_type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoe', 'Shoe'), ('accessory', 'Accessory'), ('outerwear', 'Outerwear')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet', to='closet.ClothingItem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
