# Generated by Django 2.1.14 on 2019-11-24 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('clothes', models.ManyToManyField(related_name='outfits', to='closet.ClothingItem')),
            ],
        ),
        migrations.AddField(
            model_name='closet',
            name='outfits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closet', to='closet.Outfit'),
        ),
    ]
