# Generated by Django 2.1.14 on 2019-11-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_auto_20191124_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='outfits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closet', to='closet.Outfit'),
        ),
    ]
