# Generated by Django 2.1.14 on 2019-11-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_auto_20191124_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='closet',
            name='outfits',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='closet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='closet.Closet'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='closet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='closet.Closet'),
        ),
    ]
