# Generated by Django 2.1.14 on 2019-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_auto_20191124_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
